### ISSUE TITLE
Fix chocolatey package verification errors

### ISSUE THREAD

**Issue by TraGicCode** [TechIsCool/chocolatey-newrelic-dotnet#4]
Hey @TechIsCool ,

Can you look at resolving the package validation failures for the newer versions?  

Thanks!

**Comment by TechIsCool** [comment]
@TraGicCode Can you provide the error message? The testing framework shows the last set of builds were installed successfully.

https://ci.appveyor.com/project/TechIsCool/chocolatey-newrelic-dotnet

**Comment by TraGicCode** [comment]
Hey @TechIsCool 

it’s not the build that failed, it’s that your package failed automatic validation that chocolatey has in place. It looks like the url your using for the package image is not valid/acceptable.

go here and expand versions to see your last 2 pushes require you to fix the packages


https://community.chocolatey.org/packages/newrelic-dotnet#versionhistory

**Comment by TechIsCool** [comment]
Confirmed that the fixes in #5 fixed this. If you need the older version I can hand run a job that will push it up too.
