### ISSUE TITLE
Builds Failing due to Release Version Regex

### ISSUE THREAD

**Issue by cbkob** [TechIsCool/chocolatey-newrelic-dotnet#8]
Builds Failing due to Release Version Regex

Builds seem to be failing because the Release Version Regex is capturing the version incorrectly and getting the full ".NET agent vx.x.x"

Can be fixed by updating the regex to capture the version

**Comment by cbkob** [comment]
if we can update line 22 of newrelic-dotnet.ps1 to the updated regex I tested on local and should capture fine. 
`$Version = $Sorted[0].title.InnerText -replace '(.*\bv)(\d.+)', '$2'`

**Comment by TechIsCool** [comment]
Thanks so much for Resolving this with #9, I have confirmed a new build has been cut with the newest version.
